version: "3"
services:
    oracle:
        image: oracle/database:19.3.0-ee
        ports:
            - "11521:1521"
        environment:
            - ORACLE_PWD=testing12345
    
    web:
        build:
            context: ./
            target: runner
        volumes:
            - .:/app
        command: npm run dev
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: development